### ISSUE TITLE
Can you please set Show Stats to On by default?

### ISSUE THREAD

**Issue by stefan230561** [amandel/esphome-ld2410#6]
Each time the sensor is restarted, Show Stats must be switched from Off to On so that values ​​are written to MQTT. 

But I need these values ​​to switch the light on. 

Can you please set Show Stats to On by default or tell me where and how to set it?

Thank you very much.

**Comment by ReliableBob** [comment]
Hello.
I solved this problem in this way.
```
esphome:
  name: ld2410-git1
  friendly_name: ld2410-git1
  platform: ESP8266
  board: esp12e
  includes:
    - ld2410_1.h
  on_boot:
    priority: -10
    # ...
    then:
      - switch.turn_on: show_stats
```
